#!/bin/bash

##
# Author: Himbeertoni
# Email: Toni.Himbeer@fn.de
# Github: https://www.github.com/himbeer-toni
# 
# This script is available for
# public use under GPL V3 (see
# https://www.gnu.org/licenses/gpl-3.0.en.html )
# 
# ©2025 Himbeertoni
# 
##
# Very personal helper
#  to open a file remotely on smartphone and
#  copy it back when written remotely
#  e. g. to use Markor-app to edit markdown
#  mmainly useful when you ssh-ed from your
#  phone to your system.
# pre-reqirements:
#  - Termux installed on smartphone
#  - passwordless (using ssh-keys) ssh-access to termux
#    on smartphone
#  - inotifywait installed in termux

# your phone's hostname, directory
phone=s24
phonedir=st/download

# File to work on is arg #1, get extension
# (will be needed for tmpfil, otherwise termux
# has no (or at least - no good) idea which App
# is appropriate for "termux-open"
src=$1
ext=".${src/*./}"
tmpfil=$(mktemp -u "tmp-XXXXXXXX.${ext}")

# copy it over ..
scp -q "$src" ${phone}:"${phonedir}/${tmpfil}"
# .. open it there ..
ssh ${phone} "termux-open \"${phonedir}/${tmpfil}\""
# .. wait until it is written ..
ssh ${phone} "inotifywait -qqe CLOSE_WRITE \"${phonedir}/${tmpfil}\""
# .. copy it back ..
scp -q ${phone}:"${phonedir}/${tmpfil}" "${tmpfil}"
# .. and remove tmpfil
ssh ${phone} "rm -f \"${phonedir}/${tmpfil}\""
# if file-from-remote differs from src, replace src
# while preserving mode
prvmod=$(stat -c %a "${src}")
diff -q "$tmpfil" "$src" > /dev/null
[ $? != 0 ] && mv "${tmpfil}" "${src}" && chmod $prvmod "$src"
exit
